### ISSUE TITLE
Pytest ^5.2 doesn't work on Python 3.11

### ISSUE THREAD

**Issue by perennialAutodidact** [pyn-sol/detaMVC#2]
Running `pytest^5.2` causes the following error when run with Python 3.11. Is Python 3.8 required for other dependencies? Upgrading to `pytest^6.2.5` resolves the issue, but I haven't checked if that version of `pytest` is compatible with Python 3.8. 

```
$ poetry run pytest .\tests\test_detamvc.py   

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                                         ^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "C:\Users\keego\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\assertion\rewrite.py", line 143, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keego\AppData\Local\pypoetry\Cache\virtualenvs\detamvc-m0gwfM60-py3.11\Lib\site-packages\_pytest\assertion\rewrite.py", line 330, in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: required field "lineno" missing from alias
```

**Comment by pyn-sol** [comment]
I wasn't aware of that incompatibility - we could probably change the dependency in the pyproject.toml from `pytest = "^5.2"` to `pytest = ">=5.2"`
